#!/bin/bash

# Originally from https://github.com/rust-lang/rust/issues/36710#issuecomment-364623950

args=()

for arg in "$@"; do
	if [[ $arg = *"Bdynamic"* ]]; then
		args+=() # we do not want this arg
	elif [[ $arg = *"crti.o"* ]]; then
		args+=("$arg" "/opt/cross/lib/gcc/x86_64-linux-musl/9.2.0/crtbeginS.o" "-Bstatic")
	elif [[ $arg = *"crtn.o"* ]]; then
		args+=("-lgcc" "-lgcc_eh" "-lc" "/opt/cross/lib/gcc/x86_64-linux-musl/9.2.0/crtendS.o" "$arg")
	else
		args+=("$arg")
	fi
done

# echo "RUNNING WITH ARGS: ${args[@]}"
/opt/cross/bin/x86_64-linux-musl-g++ "${args[@]}"
